_target_: navsim.agents.mimir_grpo.mimir_agent.MimirAgent
_convert_: 'all'

config:
  _target_: navsim.agents.mimir_grpo.mimir_config.MimirConfig
  _convert_: 'all'

  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.5

  latent: False
  training: True
  use_proj_image: False
  use_gt_goal_train: False
  status_norm: False
  use_unc_score: True
  use_wm: True
  grpo: True
  grpo_sample_time: 8
  grpo_num_samples_per_anchor: 1
  grpo_bc_coeff: 0.1

  navi_path: ''
  unc_path: ''

  goal_coord_path: null
  navi_unc_outputdir: null
checkpoint_path: null
lr: 2.5e-5
traj_save_path: null
