_target_: navsim.agents.mimir_rl.mimir_rl_agent.MimirRlAgent
_convert_: 'all'

config:
  _target_: navsim.agents.mimir_rl.mimir_rl_config.MimirConfig
  _convert_: 'all'

  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.5

  latent: False
  training: False
  use_proj_image: False
  use_gt_goal_train: True
  status_norm: False
  use_unc_score: False
  use_wm: True
  wm_num_future_frames: 3
  wm_reward_num_future_frames: 1
  num_goal_points: 1
  num_groups: 4

  navi_path: ''
  unc_path: ''

  goal_coord_path: null
  navi_unc_outputdir: null
checkpoint_path: null
lr: 2.5e-5
